### ISSUE TITLE
Hard Attention-GAT Error

### ISSUE THREAD

**Issue by xinhaoH** [CORE-Robotics-Lab/MAGIC#1]
sh train_pp_medium.sh
error info:
![error](https://user-images.githubusercontent.com/39089809/117602169-9c3c6280-b182-11eb-8612-f30fa2cd8ad4.jpg)

**Comment by chrisyrniu** [comment]
Dear Xinhao,

Thanks for your interest! First I think you are using an older version of PyTorch (e.g. v0.4.x, v1.0.x), and the old gumbel_softmax function will trigger this shape error. Please update your PyTorch to v1.5.0! I also noticed that you revised original "magic.py" and that might also have an impact on the error.

We would invite you to reach out to us at <yaruniu@gatech.edu> to chat about how we can support you in exploring our codebase!

Best regards,
Yaru

**Comment by xinhaoH** [comment]
Thanks a lot! 

> Dear Xinhao,
> 
> Thanks for your interest! First I think you are using an older version of PyTorch (e.g. v0.4.x, v1.0.x), and the old gumbel_softmax function will trigger this shape error. Please update your PyTorch to v1.5.0! I also noticed that you revised original "magic.py" and that might also have an impact on the error.
> 
> We would invite you to reach out to us at [yaruniu@gatech.edu](mailto:yaruniu@gatech.edu) to chat about how we can support you in exploring our codebase!
> 
> Best regards,
> Yaru
