### ISSUE TITLE
Running Magic on other environment

### ISSUE THREAD

**Issue by Rza-A** [CORE-Robotics-Lab/MAGIC#5]
Hello and thank you for your code.

I'd like to run MAGIC on other Gym based multi-agent environments. 

After checking the code, I realized that we need to write a wrapper for the environments and overload action space, observation space, reset, step, etc. However, I have a doubt. Since MAGIC is a communication-based method. Do we also need to modify the environment to allow some sort of communication between agents? 

Best regards,
Rza

**Comment by chrisyrniu** [comment]
Hi Rza,

Thanks for your interests in our work and codebase!

To run MAGIC on a new environment, there is no requirement to revise the environment (e.g., changing the observation or action space) to facilitate communication among agents. The communication protocol is integrated with and handled by the policy network of our method.

Having said that, you might still consider environment settings that are related to partial observability and communication, such as the permissible range of observation or allowed range of communication (which can impose a mask on the learned communication graphs).

Please let us know if you have further questions on applying MAGIC to your new environment.

Best regards,
Yaru

**Comment by Rza-A** [comment]
Thank you for your Response Yaru.

Would you please clarify what the[ `self.stat['success']` ](https://github.com/CORE-Robotics-Lab/MAGIC/blob/af608fda8e31d6c9acd5a63f8b55db1f0cd04f12/envs/grf-envs/grf_envs/grf_wrapper_env.py#L87)variable does? and does it have any effect on the training of the model?

Best regards,
Reza

**Comment by chrisyrniu** [comment]
Hi Reza,

`self.stat[''success]` is used to calculate the success rate of the task (in GRF/TJ) to monitor and evaluate the model's performance, while it will not affect the model training. Please refer to [`get_stat`](https://github.com/CORE-Robotics-Lab/MAGIC/blob/af608fda8e31d6c9acd5a63f8b55db1f0cd04f12/env_wrappers.py#L102), [`merge_stat`](https://github.com/CORE-Robotics-Lab/MAGIC/blob/af608fda8e31d6c9acd5a63f8b55db1f0cd04f12/utils.py#L15C1-L15C27), and [`run_batch`](https://github.com/CORE-Robotics-Lab/MAGIC/blob/af608fda8e31d6c9acd5a63f8b55db1f0cd04f12/trainer.py#L201) to understand how the data is utilized and processed.

Best regards,
Yaru
