### ISSUE TITLE
Problems related to MAGIC and baselines in GRF environment

### ISSUE THREAD

**Issue by GP413413** [CORE-Robotics-Lab/MAGIC#7]
Thank you for your reply. Actually, I am working on multi-agent cooperative communication, and recently focus on the Google Research Football environment. I find that most works on GRF environment, like https://github.com/PKU-MARL/Multi-Agent-Transformer, support 3 vs 1 academy scenario but do not support 11 vs 11 hard game scenario. 
Recently I have found the MARL version of GRF environment including 11 vs 11 full game, https://github.com/jidiai/GRF_MARL, which have algorithms such as MAPPO HAPPO MAT. It is also wrapped over the origin gfootball lib. I want to tranfer that version of GRF_MARL environment into MAGIC repo for testing, but I have met some difficulties since their frameworks differ a lot. I am still trying to find some ways to solve it. Any suggestions from you are valuable :)
Thank you for your help.

**Comment by chrisyrniu** [comment]
Glad talked to you through a video chat and I'm closing this issue.
